version: 2.1
executors:
  pyinstaller:
    docker:
      - image: amazonlinux:2
jobs:
  build-binary:
    executor: pyinstaller
    steps:
      - checkout
      - run: ldd --version
      - run: yum install -y git gcc make zlib-devel bzip2 bzip2-devel readline-devel sqlite sqlite-devel openssl-devel xz xz-devel libffi-devel findutils
      - run: ldd --version
      - run: curl https://pyenv.run | bash
            
      - run: ~/.pyenv/bin/pyenv version
      - run: ~/.pyenv/bin/pyenv install 3.8
      - run: ~/.pyenv/bin/pyenv global 3.8
      - run: python --version
      - run: python -m pip install --no-cache-dir pipenv
      - run: pipenv run pip install pyinstaller
      - run: ldd --version
      - run: pipenv run pip install semgrep==1.52.0 --target ./semgrepinstall
      - run: >
          { echo '#!/usr/bin/env python3'; cat ./semgrepinstall/semgrep/main.py;
          echo 'sys.exit(main())';} > tempfile

          mv tempfile ./semgrepinstall/semgrep/main.py

          cp ./semgrepinstall/semgrep/main.py
          ./semgrepinstall/semgrep/__main__.py

          cat ./semgrepinstall/semgrep/main.py
      - run:  pipenv run pyinstaller semgrep.spec
      - store_artifacts:
          path: dist/semgrep
          destination: semgrep-linux
workflows:
  binary-builder:
    jobs:
      - build-binary
