version: 2.1
executors:
  pyinstaller:
    docker:
      - image: amazonlinux:2
jobs:
  build-binary:
    executor: pyinstaller
    steps:
      - checkout
      - run: ldd --version
      - run: yum install -y git gcc make zlib-devel bzip2 bzip2-devel readline-devel sqlite sqlite-devel openssl-devel xz xz-devel libffi-devel findutils tar
      - run: ldd --version
      - run: curl https://pyenv.run | bash
      - run:
             export PYENV_ROOT="$HOME/.pyenv"
             
             export PATH="$PYENV_ROOT/bin:$PATH"
             
             eval "$(pyenv init --path)"
             
             eval "$(pyenv init -)"

             pyenv version

             pyenv install 3.8

             pyenv global 3.8

             python --version

             pip install pyinstaller

             ldd --version

             pip install semgrep==1.52.0 --target ./semgrepinstall

             { echo '#!/usr/bin/env python3'; cat ./semgrepinstall/semgrep/main.py;
             echo 'sys.exit(main())';} > tempfile

             mv tempfile ./semgrepinstall/semgrep/main.py

             cp ./semgrepinstall/semgrep/main.py
             ./semgrepinstall/semgrep/__main__.py

             cat ./semgrepinstall/semgrep/main.py

             pyinstaller semgrep.spec
      - run: chmod +x dist/semgrep
      - run: zip -j semgrep.zip dist/semgrep
      - store_artifacts:
          path: dist/semgrep.zip
          destination: semgrep-linux
workflows:
  binary-builder:
    jobs:
      - build-binary
